In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# 平方根
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
# 自然対数の底
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
# 正規分布に従う乱数を生成
A = np.random.randn(10)
A

array([-0.1229158 ,  1.96328265,  0.49176278,  0.52738149,  1.33216874,
        0.49954676, -0.20963439,  1.27650394,  0.25177798,  0.75235727])

In [7]:
B = np.random.randn(10)
B

array([-1.26123133, -1.40075156, -1.4347728 , -0.9081594 , -0.3157513 ,
       -0.48062111, -0.52018586, -2.39338577,  2.26064895,  0.50759154])

In [8]:
# 足し算
np.add(A, B)

array([-1.38414712,  0.56253109, -0.94301002, -0.38077792,  1.01641745,
        0.01892565, -0.72982025, -1.11688183,  2.51242693,  1.25994881])

In [9]:
# 各要素の大きい方をとる
np.maximum(A, B)

array([-0.1229158 ,  1.96328265,  0.49176278,  0.52738149,  1.33216874,
        0.49954676, -0.20963439,  1.27650394,  2.26064895,  0.75235727])