In [1]:
import numpy as np

In [2]:
# Pythonの配列からarrayを作る
my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [4]:
# リストのリストを作成
my_list2 = [11, 22, 33, 44]
my_lists = [my_list1, my_list2]
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [6]:
# 多次元配列のarrayを作成(2行4列)
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [7]:
# 配列の確認
my_array2.shape

(2, 4)

In [8]:
# データ型の確認
my_array2.dtype

dtype('int64')

## 注意
- Numpyのリスト内のデータ型は全て同じである必要がある
- Pythonのリストは同じである必要がない

In [9]:
# 全ての値が0のarrayを作る
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [10]:
# 全ての値が0のarrayを作り、整数で表示
np.zeros((5), dtype=np.int16)

array([0, 0, 0, 0, 0], dtype=int16)

In [11]:
# np.zerosのデータ型を確認
my_zeros = np.zeros(5)
my_zeros.dtype

dtype('float64')

In [12]:
# np.zeros((5), dtype=np.int16)のデータ型を確認
my_zeros = np.zeros((5), dtype=np.int16)
my_zeros

array([0, 0, 0, 0, 0], dtype=int16)

In [14]:
# 全ての要素が1のarrayを作る
np.ones((5, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
# np.ones((5, 5))のデータ型確認
ones = np.ones((5, 5))
ones.dtype

dtype('float64')

In [17]:
# 全ての要素が1でint型のarrayを作る
np.ones((5, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# 全ての要素が1でint型のarrayのデータ型を確認
ones = np.ones((5, 5), dtype=int)
ones.dtype

dtype('int64')

In [20]:
# 空のarrayを作成
np.empty((3, 4))

array([[  2.68156159e+154,  -1.73059668e-077,   2.96439388e-323,
          4.94065646e-324],
       [  0.00000000e+000,   2.42336491e-057,   0.00000000e+000,
          4.08370670e-033],
       [  0.00000000e+000,   1.10524429e+165,   0.00000000e+000,
          8.38734976e-309]])

## 注意
- np.emptyで数字が入っているが、空のarrayを生成している
- 空と0は異なる
- 0にするにはzerosを使用する

In [23]:
# 単位行列
## 5行5列で対角線に1が並ぶarray
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [24]:
# ０から指定した数だけarrayを作る
np.arange(5)

array([0, 1, 2, 3, 4])

In [25]:
# 開始と終わりと飛ばす数を指定
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])