In [1]:
import numpy as np

In [2]:
5 / 2

2.5

In [3]:
# Python2系の場合には整数の割り算でfloatが返らないので、以下を実行
from __future__ import division

In [5]:
# 多次元の配列
arr1 = np.array([[1, 2, 3, 4], [8, 9, 10, 11]])

In [6]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [7]:
# それぞれの要素の掛け算
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
# それぞれの要素の引き算
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
# 足し算
arr1 + arr1

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [10]:
# 割り算
arr1 / arr1

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [11]:
# 1を各要素で割る
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [12]:
# べき乗の計算
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])