In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [5]:
# バイナリデータとして保存
np.save('my_array', arr)

In [7]:
# 保存したarrayのload
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [10]:
arr2 = np.arange(10)

In [11]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1 = np.load('my_array.npy')

In [13]:
arr1

array([0, 1, 2, 3, 4])

In [18]:
# 複数のアレイをzip形式で保存
np.savez('ziparray.npz', x=arr1, y=arr2)

In [19]:
# zipの読み込み
archive_array = np.load('ziparray.npz')

In [20]:
archive_array

In [21]:
# 名前を使ってアクセス
archive_array['x']

array([0, 1, 2, 3, 4])

In [22]:
arr = np.arange(8).reshape(2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
# テキスト形式で保存
np.savetxt('test_text.txt', arr, delimiter=',')

In [ ]:
# ファイルを確認
!cat te