In [2]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape((3, 3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 列方向に連結
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# 行方向に連結
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0, 1, 2], index=['T', 'U', 'V'])
ser2 = Series([3, 4], index=['X', 'Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [10]:
# 行方向に連結
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
# 列方向に連結
pd.concat([ser1, ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [17]:
# 行方向に階層的なインデックスを作成
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [18]:
# 列方向に階層的なインデックスを作成
pd.concat([ser1, ser2], axis=1, keys=['cat1', 'cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [19]:
df1 = DataFrame(np.random.randn(4, 3), columns=['X', 'Y', 'Z'])
df1

X         Y         Z
0  0.717524  0.713822 -1.328463
1  1.112631  1.068848  0.114251
2  1.367937 -0.973109  0.092702
3  0.615487  1.182197 -0.511885

In [20]:
df2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [21]:
df2

Y         Q         X
0 -0.825976 -0.377329  0.321306
1 -0.393271  0.576348  0.419991
2 -0.567578 -0.255078 -1.628989

In [22]:
pd.concat([df1, df2])

Q         X         Y         Z
0       NaN  0.717524  0.713822 -1.328463
1       NaN  1.112631  1.068848  0.114251
2       NaN  1.367937 -0.973109  0.092702
3       NaN  0.615487  1.182197 -0.511885
0 -0.377329  0.321306 -0.825976       NaN
1  0.576348  0.419991 -0.393271       NaN
2 -0.255078 -1.628989 -0.567578       NaN