In [1]:
import numpy as np

In [2]:
# 3行3列のarrayを作成
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# 行と列を入れ替える(転置)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [4]:
# 上記と同じ
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [5]:
# transpose(行, 列)
arr.transpose((0, 1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 行と列を入れ替え
arr.transpose((1, 0))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [8]:
# 軸を入れ替える場合
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [9]:
# 上記と同じ
arr.swapaxes(1, 0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [10]:
# 行列の掛け算を実行
np.dot(arr.T, arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [12]:
# 三次元のarrayを作成
arr_3d = np.arange(12).reshape(3, 2, 2)
arr_3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [13]:
# 最初の要素
arr_3d[0]

array([[0, 1],
       [2, 3]])